//
//  ImageSearchModels.swift
//  Clean_Swift_Architecture_Example
//
//  Created by ADMIN on 24/05/20.
//  Copyright (c) 2020 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ImageSearch
{
  // MARK: Use cases
  
  enum SearchContents
  {
    struct Request
    {
        var searchKeywordURL = "https://suggestqueries.google.com/complete/search?client=firefox&q="
    }
    struct Response
    {
        typealias SearchKeyWord = [String]
    }
    struct ViewModel
    {
    }
  }
}
