//
//  ImageSearchWorker.swift
//  Clean_Swift_Architecture_Example
//
//  Created by ADMIN on 24/05/20.
//  Copyright (c) 2020 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ImageSearchWorker
{
  func getingSearchKeyWordListWork(url: String, header: [String: String]?, completionHandler: @escaping (Data) -> Void)
  {
    CommonObjects.shared.getAPIServiceCall(url: url, header: header){ data in
        do {
            let json = try JSONSerialization.jsonObject(with: data, options: []) as? [Any]
            let newJson = json![1] as! [String]
            completionHandler(try JSONSerialization.data(withJSONObject: newJson, options: []))
        } catch let err {
            print(err)
        }
    }
  }
}
