//
//  ImageSearchPresenter.swift
//  Clean_Swift_Architecture_Example
//
//  Created by ADMIN on 24/05/20.
//  Copyright (c) 2020 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageSearchPresentationLogic
{
    func presentSearchKeyWordList(response: ImageSearch.SearchContents.Response.SearchKeyWord)
}

class ImageSearchPresenter: ImageSearchPresentationLogic
{
  weak var viewController: ImageSearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSearchKeyWordList(response: ImageSearch.SearchContents.Response.SearchKeyWord)
  {
    let viewModel = response
    viewController?.displayKeywordList(viewModel: viewModel)
  }
}
