//
//  HomeWorker.swift
//  Clean_Swift_Architecture_Example
//
//  Created by ADMIN on 21/05/20.
//  Copyright (c) 2020 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
    func gettingTheImageWork(url: String, header: [String: String], completionHandler: @escaping (Data) -> Void)
  {
    let request = NSMutableURLRequest(url: NSURL(string: url)! as URL,
                                            cachePolicy: .useProtocolCachePolicy,
                                        timeoutInterval: 10.0)
    request.httpMethod = "GET"
    request.allHTTPHeaderFields = header

    let session = URLSession.shared
    let dataTask = session.dataTask(with: request as URLRequest, completionHandler: { (data, response, error) -> Void in
      if (error != nil) {
        print(error!)
      } else {
        guard let data = data else {return}
        completionHandler(data)
      }
    })
    dataTask.resume()
  }
}
