//
//  HomeInteractor.swift
//  Clean_Swift_Architecture_Example
//
//  Created by ADMIN on 21/05/20.
//  Copyright (c) 2020 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func getParsedJSONList(request: Home.ImageList.Request.HomePage)
    func getImageSearchJSONList(request: Home.ImageList.Request.SearchAction)
}

protocol HomeDataStore
{
    var imageDataModdel: Home.ImageList.Response.ImageListModel! { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var imageDataModdel: Home.ImageList.Response.ImageListModel!
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  
  // MARK: Do something
  
    func getParsedJSONList(request: Home.ImageList.Request.HomePage)
  {
    worker = HomeWorker()
    worker?.gettingTheImageWork(url: request.homePageURL, header: request.header, completionHandler: { data in
        do {
            let unsplashResponse = try JSONDecoder().decode(Home.ImageList.Response.ImageListModel.self, from: data)
            self.presenter?.presentParsedImageList(response: unsplashResponse)
        } catch {
            print(error)
        }
    })
  }
    
    func getImageSearchJSONList(request: Home.ImageList.Request.SearchAction)
    {
      worker = HomeWorker()
        worker?.gettingTheImageWork(url: request.unsplashSearchURL, header: nil, completionHandler: { data in
          do {
            let json = try JSONSerialization.jsonObject(with: data, options: []) as? [String: Any]
            let newJson = json?["results"]
            let unsplashResponse = try JSONDecoder().decode(Home.ImageList.Response.ImageListModel.self, from: try JSONSerialization.data(withJSONObject: newJson!, options: []))
              self.presenter?.presentParsedImageList(response: unsplashResponse)
          } catch {
              print(error)
          }
      })
    }
}
