//
//  HomeInteractor.swift
//  Clean_Swift_Architecture_Example
//
//  Created by ADMIN on 21/05/20.
//  Copyright (c) 2020 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func getParsedJSONList(request: Home.ImageList.Request)
//    func setImageDataStore(_ data: Home.ImageList.Response.ImageListModel)
}

protocol HomeDataStore
{
    var imageDataModdel: Home.ImageList.Response.ImageListModel! { get set }
    
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    
    var imageDataModdel: Home.ImageList.Response.ImageListModel!
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  
  // MARK: Do something
  
  func getParsedJSONList(request: Home.ImageList.Request)
  {
    worker = HomeWorker()
    worker?.gettingTheImageWork(url: request.baseURL, header: request.header, completionHandler: { data in
        do {
            let youtubeResponse = try JSONDecoder().decode(Home.ImageList.Response.ImageListModel.self, from: data)
            self.presenter?.presentParsedImageList(response: youtubeResponse)
        } catch {
            print(error)
        }
    })
  }
//    func setImageDataStore(_ data: Home.ImageList.Response.ImageListModel) {
//        imageDataModdel = data
//    }
}
